apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-site-deployment
  labels:
    app: mini-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mini-site
  template:
    metadata:
      labels:
        app: mini-site
    spec:
      containers:
        - name: mini-site
          image: nginx:latest   # <---- TROCA AQUI
          ports:
            - containerPort: 80
